### ISSUE TITLE
only exports jpeg

### ISSUE THREAD

**Issue by cronos45** [majimboo/mviewer#7]
/Volumes/Pennyworth1/do3d\ fileupdate/mviewer-1.0/extract_mview.py /Volumes/Pennyworth1/do3d\ fileupdate/mviewer-1.0/test_data/test_file1.mview 
('thumbnail.jpg', 'image/jpeg')
Traceback (most recent call last):
  File "/Volumes/Pennyworth1/do3d fileupdate/mviewer-1.0/extract_mview.py", line 117, in <module>
    main(sys.argv[1])
  File "/Volumes/Pennyworth1/do3d fileupdate/mviewer-1.0/extract_mview.py", line 26, in main
    data = decompress(data, e)
  File "/Volumes/Pennyworth1/do3d fileupdate/mviewer-1.0/extract_mview.py", line 58, in decompress
    p = (m << 4 | n >> 4) if r & 1 else ((m & 15) << 8 | n)
TypeError: unsupported operand type(s) for <<: 'str' and 'int'

**Comment by gormlykeep** [comment]
Same thing

C:\mview\windows\Fury.mview
('thumbnail.jpg', 'image/jpeg')
Traceback (most recent call last):
  File "C:\mview\windows\extract_mview.py", line 117, in <module>
    main(sys.argv[1])
  File "C:\mview\windows\extract_mview.py", line 26, in main
    data = decompress(data, e)
  File "C:\mview\windows\extract_mview.py", line 58, in decompress
    p = (m << 4 | n >> 4) if r & 1 else ((m & 15) << 8 | n)
TypeError: unsupported operand type(s) for <<: 'str' and 'int'

**Comment by Mactastic1-5** [comment]
Are you using Python 3? python --version

**Comment by majimboo** [comment]
Closing as a duplicate of #5. This reports the same `decompress` TypeError in `extract_mview.py`.

**Comment by majimboo** [comment]
Follow-up: this issue belonged to the old extraction path.

The current 2.x exporter has replaced that workflow with a Rust-native .mview exporter and broader scene export support.

Latest release:
https://github.com/majimboo/mviewer/releases/latest
